# ==============================================
# LANGUAGES FILE - 30+ Languages
# India: Hindi, English, Sanskrit + Top Telegram Countries
# ==============================================

# ==============================================
# INDIA - MAIN LANGUAGES
# ==============================================

# 1. Hindi (हिंदी) - Most spoken in India
HI = {
    'name': 'हिंदी',
    'country': '🇮🇳 India',
    'flag': '🇮🇳',
    'welcome': "🌟 **मेंशन बॉट में आपका स्वागत है!** 🌟",
    'your_info': "**आपकी जानकारी:**",
    'user_id': "• आपकी ID: `{user_id}`",
    'status': "• स्थिति: {status}",
    'admin_status': "👑 एडमिन",
    'user_status': "👤 यूजर",
    'owner': "• बॉट मालिक: `{owner_id}`",
    'support_btn': "📞 सपोर्ट",
    'add_btn': "➕ ग्रुप में जोड़ें",
    'settings_btn': "⚙️ सेटिंग्स",
    'language_btn': "🌐 भाषा",
    'commands_btn': "📋 कमांड्स",
    'close_btn': "❌ बंद करें",
    'back_btn': "🔙 वापस",
    'admin_only': "❌ केवल एडमिन इस कमांड का उपयोग कर सकते हैं!",
    'group_only': "⚠️ यह कमांड केवल ग्रुप में काम करती है!",
    'stopped': "⚠️ इस ग्रुप में मेंशन बंद हैं। /resume से चालू करें।",
    'user_not_found': "❌ यूजर नहीं मिला!",
    'promoted': "✅ **एडमिन बनाया गया!**",
    'demoted': "✅ **एडमिन हटाया गया!**",
    'already_admin': "⚠️ यूजर पहले से एडमिन है!",
    'not_admin': "⚠️ यूजर एडमिन नहीं है!",
    'broadcast_start': "📢 **ब्रॉडकास्ट शुरू...**",
    'broadcast_done': "✅ **ब्रॉडकास्ट पूरा हुआ!**",
    'broadcast_usage': "⚠️ उपयोग: `/broadcast [संदेश]`",
    'stats_title': "📊 **बॉट आंकड़े**",
    'total_groups': "• कुल ग्रुप: {count}",
    'total_users': "• कुल यूजर: {count}",
    'total_admins': "• कुल एडमिन: {count}",
    'bot_version': "• वर्जन: 5.0",
}

# 2. English (India/Global)
EN = {
    'name': 'English',
    'country': '🇬🇧 Global',
    'flag': '🇬🇧',
    'welcome': "🌟 **Welcome to Mention Bot!** 🌟",
    'your_info': "**Your Information:**",
    'user_id': "• Your ID: `{user_id}`",
    'status': "• Status: {status}",
    'admin_status': "👑 ADMIN",
    'user_status': "👤 USER",
    'owner': "• Bot Owner: `{owner_id}`",
    'support_btn': "📞 Support",
    'add_btn': "➕ Add to Group",
    'settings_btn': "⚙️ Settings",
    'language_btn': "🌐 Language",
    'commands_btn': "📋 Commands",
    'close_btn': "❌ Close",
    'back_btn': "🔙 Back",
    'admin_only': "❌ Only admins can use this command!",
    'group_only': "⚠️ This command only works in groups!",
    'stopped': "⚠️ Mentions are stopped in this group. Use /resume to start again.",
    'user_not_found': "❌ User not found!",
    'promoted': "✅ **Admin Promoted!**",
    'demoted': "✅ **Admin Demoted!**",
    'already_admin': "⚠️ User is already an admin!",
    'not_admin': "⚠️ User is not an admin!",
    'broadcast_start': "📢 **Broadcast starting...**",
    'broadcast_done': "✅ **Broadcast Complete!**",
    'broadcast_usage': "⚠️ Usage: `/broadcast [message]`",
    'stats_title': "📊 **Bot Statistics**",
    'total_groups': "• Total Groups: {count}",
    'total_users': "• Total Users: {count}",
    'total_admins': "• Total Admins: {count}",
    'bot_version': "• Version: 5.0",
}

# 3. Sanskrit (संस्कृतम्) - Ancient Indian Language
SA = {
    'name': 'संस्कृतम्',
    'country': '🇮🇳 India',
    'flag': '🇮🇳',
    'welcome': "🌟 **मेन्शन बॉटे स्वागतम्!** 🌟",
    'your_info': "**भवतः सूचना:**",
    'user_id': "• भवतः ID: `{user_id}`",
    'status': "• स्थिति: {status}",
    'admin_status': "👑 प्रशासकः",
    'user_status': "👤 उपयोक्ता",
    'owner': "• बॉट स्वामी: `{owner_id}`",
    'support_btn': "📞 साहाय्यम्",
    'add_btn': "➕ गणे योजयतु",
    'settings_btn': "⚙️ सेटिङ्ग्स",
    'language_btn': "🌐 भाषा",
    'commands_btn': "📋 आदेशाः",
    'close_btn': "❌ पिदधातु",
    'back_btn': "🔙 प्रत्यागच्छतु",
    'admin_only': "❌ केवलं प्रशासकाः एतम् आदेशं प्रयोक्तुं शक्नुवन्ति!",
    'group_only': "⚠️ एषः आदेशः केवलं गणेषु कार्यं करोति!",
    'stopped': "⚠️ अस्मिन् गणे मेन्शन् स्थगिताः सन्ति। /resume द्वारा पुनः आरभ्यताम्।",
    'user_not_found': "❌ उपयोक्ता न प्राप्तः!",
    'promoted': "✅ **प्रशासकः कृतः!**",
    'demoted': "✅ **प्रशासकः निष्कासितः!**",
    'already_admin': "⚠️ उपयोक्ता पूर्वमेव प्रशासकः अस्ति!",
    'not_admin': "⚠️ उपयोक्ता प्रशासकः नास्ति!",
    'broadcast_start': "📢 **प्रसारणम् आरभ्यते...**",
    'broadcast_done': "✅ **प्रसारणम् सम्पूर्णम्!**",
    'broadcast_usage': "⚠️ उपयोगः: `/broadcast [सन्देशः]`",
    'stats_title': "📊 **बॉट सांख्यिकी**",
    'total_groups': "• कुल गणाः: {count}",
    'total_users': "• कुल उपयोक्तारः: {count}",
    'total_admins': "• कुल प्रशासकाः: {count}",
    'bot_version': "• संस्करणम्: 5.0",
}

# ==============================================
# ASIA - TOP TELEGRAM COUNTRIES
# ==============================================

# 4. Indonesian (Bahasa Indonesia) - Indonesia
ID = {
    'name': 'Bahasa Indonesia',
    'country': '🇮🇩 Indonesia',
    'flag': '🇮🇩',
    'welcome': "🌟 **Selamat Datang di Mention Bot!** 🌟",
    'your_info': "**Informasi Anda:**",
    'user_id': "• ID Anda: `{user_id}`",
    'status': "• Status: {status}",
    'admin_status': "👑 ADMIN",
    'user_status': "👤 PENGGUNA",
    'owner': "• Pemilik Bot: `{owner_id}`",
    'support_btn': "📞 Dukungan",
    'add_btn': "➕ Tambah ke Grup",
    'settings_btn': "⚙️ Pengaturan",
    'language_btn': "🌐 Bahasa",
    'commands_btn': "📋 Perintah",
    'close_btn': "❌ Tutup",
    'back_btn': "🔙 Kembali",
    'admin_only': "❌ Hanya admin yang bisa menggunakan perintah ini!",
    'group_only': "⚠️ Perintah ini hanya berfungsi di grup!",
    'stopped': "⚠️ Mention di grup ini dihentikan. Gunakan /resume untuk memulai lagi.",
    'user_not_found': "❌ Pengguna tidak ditemukan!",
    'promoted': "✅ **Admin Dipromosikan!**",
    'demoted': "✅ **Admin Diturunkan!**",
    'already_admin': "⚠️ Pengguna sudah menjadi admin!",
    'not_admin': "⚠️ Pengguna bukan admin!",
    'broadcast_start': "📢 **Siaran dimulai...**",
    'broadcast_done': "✅ **Siaran Selesai!**",
    'broadcast_usage': "⚠️ Penggunaan: `/broadcast [pesan]`",
    'stats_title': "📊 **Statistik Bot**",
    'total_groups': "• Total Grup: {count}",
    'total_users': "• Total Pengguna: {count}",
    'total_admins': "• Total Admin: {count}",
    'bot_version': "• Versi: 5.0",
}

# 5. Malay (Bahasa Melayu) - Malaysia
MS = {
    'name': 'Bahasa Melayu',
    'country': '🇲🇾 Malaysia',
    'flag': '🇲🇾',
    'welcome': "🌟 **Selamat Datang ke Mention Bot!** 🌟",
    'your_info': "**Maklumat Anda:**",
    'user_id': "• ID Anda: `{user_id}`",
    'status': "• Status: {status}",
    'admin_status': "👑 ADMIN",
    'user_status': "👤 PENGGUNA",
    'owner': "• Pemilik Bot: `{owner_id}`",
    'support_btn': "📞 Sokongan",
    'add_btn': "➕ Tambah ke Kumpulan",
    'settings_btn': "⚙️ Tetapan",
    'language_btn': "🌐 Bahasa",
    'commands_btn': "📋 Perintah",
    'close_btn': "❌ Tutup",
    'back_btn': "🔙 Kembali",
    'admin_only': "❌ Hanya admin boleh menggunakan arahan ini!",
    'group_only': "⚠️ Arahan ini hanya berfungsi dalam kumpulan!",
    'stopped': "⚠️ Mention dalam kumpulan ini dihentikan. Gunakan /resume untuk mulakan semula.",
    'user_not_found': "❌ Pengguna tidak dijumpai!",
    'promoted': "✅ **Admin Dinaikkan Pangkat!**",
    'demoted': "✅ **Admin Diturunkan Pangkat!**",
    'already_admin': "⚠️ Pengguna sudah menjadi admin!",
    'not_admin': "⚠️ Pengguna bukan admin!",
    'broadcast_start': "📢 **Siaran bermula...**",
    'broadcast_done': "✅ **Siaran Selesai!**",
    'broadcast_usage': "⚠️ Penggunaan: `/broadcast [mesej]`",
    'stats_title': "📊 **Statistik Bot**",
    'total_groups': "• Jumlah Kumpulan: {count}",
    'total_users': "• Jumlah Pengguna: {count}",
    'total_admins': "• Jumlah Admin: {count}",
    'bot_version': "• Versi: 5.0",
}

# 6. Filipino (Tagalog) - Philippines
TL = {
    'name': 'Tagalog',
    'country': '🇵🇭 Philippines',
    'flag': '🇵🇭',
    'welcome': "🌟 **Maligayang Pagdating sa Mention Bot!** 🌟",
    'your_info': "**Iyong Impormasyon:**",
    'user_id': "• Iyong ID: `{user_id}`",
    'status': "• Katayuan: {status}",
    'admin_status': "👑 ADMIN",
    'user_status': "👤 USER",
    'owner': "• May-ari ng Bot: `{owner_id}`",
    'support_btn': "📞 Suporta",
    'add_btn': "➕ Idagdag sa Grupo",
    'settings_btn': "⚙️ Settings",
    'language_btn': "🌐 Wika",
    'commands_btn': "📋 Utos",
    'close_btn': "❌ Isara",
    'back_btn': "🔙 Bumalik",
    'admin_only': "❌ Ang mga admin lang ang puwedeng gumamit nito!",
    'group_only': "⚠️ Ang utos na ito ay sa grupo lang gumagana!",
    'stopped': "⚠️ Ang mentions ay tumigil sa grupong ito. Gamitin ang /resume para muling simulan.",
    'user_not_found': "❌ Hindi mahanap ang user!",
    'promoted': "✅ **Naging Admin!**",
    'demoted': "✅ **Tinanggal sa Admin!**",
    'already_admin': "⚠️ Admin na ang user na ito!",
    'not_admin': "⚠️ Hindi admin ang user na ito!",
    'broadcast_start': "📢 **Nagsisimula ang broadcast...**",
    'broadcast_done': "✅ **Tapos na ang broadcast!**",
    'broadcast_usage': "⚠️ Gamitin: `/broadcast [mensaje]`",
    'stats_title': "📊 **Estadistika ng Bot**",
    'total_groups': "• Kabuuang Grupo: {count}",
    'total_users': "• Kabuuang User: {count}",
    'total_admins': "• Kabuuang Admin: {count}",
    'bot_version': "• Bersyon: 5.0",
}

# 7. Thai (ภาษาไทย) - Thailand
TH = {
    'name': 'ภาษาไทย',
    'country': '🇹🇭 Thailand',
    'flag': '🇹🇭',
    'welcome': "🌟 **ยินดีต้อนรับสู่ Mention Bot!** 🌟",
    'your_info': "**ข้อมูลของคุณ:**",
    'user_id': "• ID ของคุณ: `{user_id}`",
    'status': "• สถานะ: {status}",
    'admin_status': "👑 ผู้ดูแลระบบ",
    'user_status': "👤 ผู้ใช้",
    'owner': "• เจ้าของบอท: `{owner_id}`",
    'support_btn': "📞 สนับสนุน",
    'add_btn': "➕ เพิ่มในกลุ่ม",
    'settings_btn': "⚙️ การตั้งค่า",
    'language_btn': "🌐 ภาษา",
    'commands_btn': "📋 คำสั่ง",
    'close_btn': "❌ ปิด",
    'back_btn': "🔙 กลับ",
    'admin_only': "❌ เฉพาะผู้ดูแลระบบเท่านั้นที่ใช้คำสั่งนี้!",
    'group_only': "⚠️ คำสั่งนี้ใช้ได้เฉพาะในกลุ่ม!",
    'stopped': "⚠️ การกล่าวถึงหยุดในกลุ่มนี้ ใช้ /resume เพื่อเริ่มใหม่",
    'user_not_found': "❌ ไม่พบผู้ใช้!",
    'promoted': "✅ **เลื่อนเป็นผู้ดูแลระบบ!**",
    'demoted': "✅ **ลดระดับผู้ดูแลระบบ!**",
    'already_admin': "⚠️ ผู้ใช้เป็นผู้ดูแลระบบอยู่แล้ว!",
    'not_admin': "⚠️ ผู้ใช้ไม่ใช่ผู้ดูแลระบบ!",
    'broadcast_start': "📢 **กำลังเริ่มออกอากาศ...**",
    'broadcast_done': "✅ **ออกอากาศเสร็จสิ้น!**",
    'broadcast_usage': "⚠️ วิธีใช้: `/broadcast [ข้อความ]`",
    'stats_title': "📊 **สถิติบอท**",
    'total_groups': "• กลุ่มทั้งหมด: {count}",
    'total_users': "• ผู้ใช้ทั้งหมด: {count}",
    'total_admins': "• ผู้ดูแลระบบทั้งหมด: {count}",
    'bot_version': "• เวอร์ชัน: 5.0",
}

# 8. Vietnamese (Tiếng Việt) - Vietnam
VI = {
    'name': 'Tiếng Việt',
    'country': '🇻🇳 Vietnam',
    'flag': '🇻🇳',
    'welcome': "🌟 **Chào mừng đến với Mention Bot!** 🌟",
    'your_info': "**Thông tin của bạn:**",
    'user_id': "• ID của bạn: `{user_id}`",
    'status': "• Trạng thái: {status}",
    'admin_status': "👑 QUẢN TRỊ VIÊN",
    'user_status': "👤 NGƯỜI DÙNG",
    'owner': "• Chủ sở hữu Bot: `{owner_id}`",
    'support_btn': "📞 Hỗ trợ",
    'add_btn': "➕ Thêm vào Nhóm",
    'settings_btn': "⚙️ Cài đặt",
    'language_btn': "🌐 Ngôn ngữ",
    'commands_btn': "📋 Lệnh",
    'close_btn': "❌ Đóng",
    'back_btn': "🔙 Quay lại",
    'admin_only': "❌ Chỉ quản trị viên mới có thể sử dụng lệnh này!",
    'group_only': "⚠️ Lệnh này chỉ hoạt động trong nhóm!",
    'stopped': "⚠️ Mention đã dừng trong nhóm này. Sử dụng /resume để bắt đầu lại.",
    'user_not_found': "❌ Không tìm thấy người dùng!",
    'promoted': "✅ **Đã thăng chức quản trị viên!**",
    'demoted': "✅ **Đã giáng chức quản trị viên!**",
    'already_admin': "⚠️ Người dùng đã là quản trị viên!",
    'not_admin': "⚠️ Người dùng không phải quản trị viên!",
    'broadcast_start': "📢 **Đang phát sóng...**",
    'broadcast_done': "✅ **Phát sóng hoàn tất!**",
    'broadcast_usage': "⚠️ Cách dùng: `/broadcast [tin nhắn]`",
    'stats_title': "📊 **Thống kê Bot**",
    'total_groups': "• Tổng số nhóm: {count}",
    'total_users': "• Tổng số người dùng: {count}",
    'total_admins': "• Tổng số quản trị viên: {count}",
    'bot_version': "• Phiên bản: 5.0",
}

# ==============================================
# MIDDLE EAST
# ==============================================

# 9. Arabic (العربية) - Egypt, Saudi Arabia, UAE
AR = {
    'name': 'العربية',
    'country': '🇸🇦 Saudi Arabia / 🇪🇬 Egypt',
    'flag': '🇸🇦',
    'welcome': "🌟 **مرحباً بك في بوت المنشن!** 🌟",
    'your_info': "**معلوماتك:**",
    'user_id': "• معرفك: `{user_id}`",
    'status': "• الحالة: {status}",
    'admin_status': "👑 أدمن",
    'user_status': "👤 مستخدم",
    'owner': "• مالك البوت: `{owner_id}`",
    'support_btn': "📞 دعم",
    'add_btn': "➕ أضف للمجموعة",
    'settings_btn': "⚙️ إعدادات",
    'language_btn': "🌐 اللغة",
    'commands_btn': "📋 الأوامر",
    'close_btn': "❌ إغلاق",
    'back_btn': "🔙 رجوع",
    'admin_only': "❌ الأدمن فقط يمكنهم استخدام هذا الأمر!",
    'group_only': "⚠️ هذا الأمر يعمل فقط في المجموعات!",
    'stopped': "⚠️ المنشن متوقف في هذه المجموعة. استخدم /resume للبدء مجدداً.",
    'user_not_found': "❌ المستخدم غير موجود!",
    'promoted': "✅ **تمت الترقية!**",
    'demoted': "✅ **تمت الخفض!**",
    'already_admin': "⚠️ المستخدم أدمن بالفعل!",
    'not_admin': "⚠️ المستخدم ليس أدمن!",
    'broadcast_start': "📢 **بدء البث...**",
    'broadcast_done': "✅ **اكتمل البث!**",
    'broadcast_usage': "⚠️ الاستخدام: `/broadcast [رسالة]`",
    'stats_title': "📊 **إحصائيات البوت**",
    'total_groups': "• إجمالي المجموعات: {count}",
    'total_users': "• إجمالي المستخدمين: {count}",
    'total_admins': "• إجمالي الأدمن: {count}",
    'bot_version': "• الإصدار: 5.0",
}

# 10. Turkish (Türkçe) - Turkey
TR = {
    'name': 'Türkçe',
    'country': '🇹🇷 Turkey',
    'flag': '🇹🇷',
    'welcome': "🌟 **Mention Bot'a Hoş Geldiniz!** 🌟",
    'your_info': "**Bilgileriniz:**",
    'user_id': "• ID'niz: `{user_id}`",
    'status': "• Durum: {status}",
    'admin_status': "👑 ADMIN",
    'user_status': "👤 KULLANICI",
    'owner': "• Bot Sahibi: `{owner_id}`",
    'support_btn': "📞 Destek",
    'add_btn': "➕ Gruba Ekle",
    'settings_btn': "⚙️ Ayarlar",
    'language_btn': "🌐 Dil",
    'commands_btn': "📋 Komutlar",
    'close_btn': "❌ Kapat",
    'back_btn': "🔙 Geri",
    'admin_only': "❌ Bu komutu sadece adminler kullanabilir!",
    'group_only': "⚠️ Bu komut sadece gruplarda çalışır!",
    'stopped': "⚠️ Bu grupta mentionlar durduruldu. /resume ile tekrar başlatın.",
    'user_not_found': "❌ Kullanıcı bulunamadı!",
    'promoted': "✅ **Admin Yapıldı!**",
    'demoted': "✅ **Adminlik Kaldırıldı!**",
    'already_admin': "⚠️ Kullanıcı zaten admin!",
    'not_admin': "⚠️ Kullanıcı admin değil!",
    'broadcast_start': "📢 **Yayın başlıyor...**",
    'broadcast_done': "✅ **Yayın tamamlandı!**",
    'broadcast_usage': "⚠️ Kullanım: `/broadcast [mesaj]`",
    'stats_title': "📊 **Bot İstatistikleri**",
    'total_groups': "• Toplam Gruplar: {count}",
    'total_users': "• Toplam Kullanıcılar: {count}",
    'total_admins': "• Toplam Adminler: {count}",
    'bot_version': "• Sürüm: 5.0",
}

# 11. Persian (فارسی) - Iran
FA = {
    'name': 'فارسی',
    'country': '🇮🇷 Iran',
    'flag': '🇮🇷',
    'welcome': "🌟 **به بات منشن خوش آمدید!** 🌟",
    'your_info': "**اطلاعات شما:**",
    'user_id': "• ID شما: `{user_id}`",
    'status': "• وضعیت: {status}",
    'admin_status': "👑 ادمین",
    'user_status': "👤 کاربر",
    'owner': "• مالک بات: `{owner_id}`",
    'support_btn': "📞 پشتیبانی",
    'add_btn': "➕ افزودن به گروه",
    'settings_btn': "⚙️ تنظیمات",
    'language_btn': "🌐 زبان",
    'commands_btn': "📋 دستورات",
    'close_btn': "❌ بستن",
    'back_btn': "🔙 بازگشت",
    'admin_only': "❌ فقط ادمین‌ها می‌توانند از این دستور استفاده کنند!",
    'group_only': "⚠️ این دستور فقط در گروه‌ها کار می‌کند!",
    'stopped': "⚠️ منشن در این گروه متوقف شده است. از /resume برای شروع مجدد استفاده کنید.",
    'user_not_found': "❌ کاربر یافت نشد!",
    'promoted': "✅ **ادمین شد!**",
    'demoted': "✅ **ادمین حذف شد!**",
    'already_admin': "⚠️ کاربر قبلاً ادمین است!",
    'not_admin': "⚠️ کاربر ادمین نیست!",
    'broadcast_start': "📢 **پخش شروع شد...**",
    'broadcast_done': "✅ **پخش کامل شد!**",
    'broadcast_usage': "⚠️ استفاده: `/broadcast [پیام]`",
    'stats_title': "📊 **آمار بات**",
    'total_groups': "• کل گروه‌ها: {count}",
    'total_users': "• کل کاربران: {count}",
    'total_admins': "• کل ادمین‌ها: {count}",
    'bot_version': "• نسخه: 5.0",
}

# ==============================================
# EUROPE
# ==============================================

# 12. Russian (Русский) - Russia
RU = {
    'name': 'Русский',
    'country': '🇷🇺 Russia',
    'flag': '🇷🇺',
    'welcome': "🌟 **Добро пожаловать в Mention Bot!** 🌟",
    'your_info': "**Ваша информация:**",
    'user_id': "• Ваш ID: `{user_id}`",
    'status': "• Статус: {status}",
    'admin_status': "👑 АДМИН",
    'user_status': "👤 ПОЛЬЗОВАТЕЛЬ",
    'owner': "• Владелец бота: `{owner_id}`",
    'support_btn': "📞 Поддержка",
    'add_btn': "➕ Добавить в группу",
    'settings_btn': "⚙️ Настройки",
    'language_btn': "🌐 Язык",
    'commands_btn': "📋 Команды",
    'close_btn': "❌ Закрыть",
    'back_btn': "🔙 Назад",
    'admin_only': "❌ Только админы могут использовать эту команду!",
    'group_only': "⚠️ Эта команда работает только в группах!",
    'stopped': "⚠️ Упоминания остановлены в этой группе. Используйте /resume для возобновления.",
    'user_not_found': "❌ Пользователь не найден!",
    'promoted': "✅ **Админ назначен!**",
    'demoted': "✅ **Админ удален!**",
    'already_admin': "⚠️ Пользователь уже админ!",
    'not_admin': "⚠️ Пользователь не админ!",
    'broadcast_start': "📢 **Рассылка началась...**",
    'broadcast_done': "✅ **Рассылка завершена!**",
    'broadcast_usage': "⚠️ Использование: `/broadcast [сообщение]`",
    'stats_title': "📊 **Статистика бота**",
    'total_groups': "• Всего групп: {count}",
    'total_users': "• Всего пользователей: {count}",
    'total_admins': "• Всего админов: {count}",
    'bot_version': "• Версия: 5.0",
}

# 13. German (Deutsch) - Germany
DE = {
    'name': 'Deutsch',
    'country': '🇩🇪 Germany',
    'flag': '🇩🇪',
    'welcome': "🌟 **Willkommen beim Mention Bot!** 🌟",
    'your_info': "**Ihre Informationen:**",
    'user_id': "• Ihre ID: `{user_id}`",
    'status': "• Status: {status}",
    'admin_status': "👑 ADMIN",
    'user_status': "👤 BENUTZER",
    'owner': "• Bot-Besitzer: `{owner_id}`",
    'support_btn': "📞 Support",
    'add_btn': "➕ Zur Gruppe hinzufügen",
    'settings_btn': "⚙️ Einstellungen",
    'language_btn': "🌐 Sprache",
    'commands_btn': "📋 Befehle",
    'close_btn': "❌ Schließen",
    'back_btn': "🔙 Zurück",
    'admin_only': "❌ Nur Admins können diesen Befehl verwenden!",
    'group_only': "⚠️ Dieser Befehl funktioniert nur in Gruppen!",
    'stopped': "⚠️ Erwähnungen in dieser Gruppe gestoppt. Verwenden Sie /resume zum Neustarten.",
    'user_not_found': "❌ Benutzer nicht gefunden!",
    'promoted': "✅ **Admin befördert!**",
    'demoted': "✅ **Admin degradiert!**",
    'already_admin': "⚠️ Benutzer ist bereits Admin!",
    'not_admin': "⚠️ Benutzer ist kein Admin!",
    'broadcast_start': "📢 **Rundsendung startet...**",
    'broadcast_done': "✅ **Rundsendung abgeschlossen!**",
    'broadcast_usage': "⚠️ Verwendung: `/broadcast [Nachricht]`",
    'stats_title': "📊 **Bot-Statistiken**",
    'total_groups': "• Gruppen insgesamt: {count}",
    'total_users': "• Benutzer insgesamt: {count}",
    'total_admins': "• Admins insgesamt: {count}",
    'bot_version': "• Version: 5.0",
}

# 14. French (Français) - France
FR = {
    'name': 'Français',
    'country': '🇫🇷 France',
    'flag': '🇫🇷',
    'welcome': "🌟 **Bienvenue sur Mention Bot!** 🌟",
    'your_info': "**Vos informations:**",
    'user_id': "• Votre ID: `{user_id}`",
    'status': "• Statut: {status}",
    'admin_status': "👑 ADMIN",
    'user_status': "👤 UTILISATEUR",
    'owner': "• Propriétaire du bot: `{owner_id}`",
    'support_btn': "📞 Support",
    'add_btn': "➕ Ajouter au groupe",
    'settings_btn': "⚙️ Paramètres",
    'language_btn': "🌐 Langue",
    'commands_btn': "📋 Commandes",
    'close_btn': "❌ Fermer",
    'back_btn': "🔙 Retour",
    'admin_only': "❌ Seuls les admins peuvent utiliser cette commande!",
    'group_only': "⚠️ Cette commande ne fonctionne que dans les groupes!",
    'stopped': "⚠️ Les mentions sont arrêtées dans ce groupe. Utilisez /resume pour recommencer.",
    'user_not_found': "❌ Utilisateur non trouvé!",
    'promoted': "✅ **Admin promu!**",
    'demoted': "✅ **Admin rétrogradé!**",
    'already_admin': "⚠️ L'utilisateur est déjà admin!",
    'not_admin': "⚠️ L'utilisateur n'est pas admin!",
    'broadcast_start': "📢 **Diffusion commencée...**",
    'broadcast_done': "✅ **Diffusion terminée!**",
    'broadcast_usage': "⚠️ Utilisation: `/broadcast [message]`",
    'stats_title': "📊 **Statistiques du bot**",
    'total_groups': "• Total des groupes: {count}",
    'total_users': "• Total des utilisateurs: {count}",
    'total_admins': "• Total des admins: {count}",
    'bot_version': "• Version: 5.0",
}

# 15. Spanish (Español) - Spain, Latin America
ES = {
    'name': 'Español',
    'country': '🇪🇸 Spain / 🌎 Latin America',
    'flag': '🇪🇸',
    'welcome': "🌟 **¡Bienvenido a Mention Bot!** 🌟",
    'your_info': "**Tu información:**",
    'user_id': "• Tu ID: `{user_id}`",
    'status': "• Estado: {status}",
    'admin_status': "👑 ADMIN",
    'user_status': "👤 USUARIO",
    'owner': "• Dueño del Bot: `{owner_id}`",
    'support_btn': "📞 Soporte",
    'add_btn': "➕ Añadir al Grupo",
    'settings_btn': "⚙️ Ajustes",
    'language_btn': "🌐 Idioma",
    'commands_btn': "📋 Comandos",
    'close_btn': "❌ Cerrar",
    'back_btn': "🔙 Volver",
    'admin_only': "❌ ¡Solo los admins pueden usar este comando!",
    'group_only': "⚠️ ¡Este comando solo funciona en grupos!",
    'stopped': "⚠️ Las menciones están detenidas en este grupo. Usa /resume para reiniciar.",
    'user_not_found': "❌ ¡Usuario no encontrado!",
    'promoted': "✅ **¡Admin Promovido!**",
    'demoted': "✅ **¡Admin Degradado!**",
    'already_admin': "⚠️ ¡El usuario ya es admin!",
    'not_admin': "⚠️ ¡El usuario no es admin!",
    'broadcast_start': "📢 **Transmisión comenzando...**",
    'broadcast_done': "✅ **¡Transmisión Completa!**",
    'broadcast_usage': "⚠️ Uso: `/broadcast [mensaje]`",
    'stats_title': "📊 **Estadísticas del Bot**",
    'total_groups': "• Total de Grupos: {count}",
    'total_users': "• Total de Usuarios: {count}",
    'total_admins': "• Total de Admins: {count}",
    'bot_version': "• Versión: 5.0",
}

# 16. Italian (Italiano) - Italy
IT = {
    'name': 'Italiano',
    'country': '🇮🇹 Italy',
    'flag': '🇮🇹',
    'welcome': "🌟 **Benvenuto su Mention Bot!** 🌟",
    'your_info': "**Le tue informazioni:**",
    'user_id': "• Il tuo ID: `{user_id}`",
    'status': "• Stato: {status}",
    'admin_status': "👑 ADMIN",
    'user_status': "👤 UTENTE",
    'owner': "• Proprietario del Bot: `{owner_id}`",
    'support_btn': "📞 Supporto",
    'add_btn': "➕ Aggiungi al Gruppo",
    'settings_btn': "⚙️ Impostazioni",
    'language_btn': "🌐 Lingua",
    'commands_btn': "📋 Comandi",
    'close_btn': "❌ Chiudi",
    'back_btn': "🔙 Indietro",
    'admin_only': "❌ Solo gli admin possono usare questo comando!",
    'group_only': "⚠️ Questo comando funziona solo nei gruppi!",
    'stopped': "⚠️ Le menzioni sono ferme in questo gruppo. Usa /resume per riavviare.",
    'user_not_found': "❌ Utente non trovato!",
    'promoted': "✅ **Admin Promosso!**",
    'demoted': "✅ **Admin Retrocesso!**",
    'already_admin': "⚠️ L'utente è già admin!",
    'not_admin': "⚠️ L'utente non è admin!",
    'broadcast_start': "📢 **Trasmissione iniziata...**",
    'broadcast_done': "✅ **Trasmissione Completata!**",
    'broadcast_usage': "⚠️ Uso: `/broadcast [messaggio]`",
    'stats_title': "📊 **Statistiche del Bot**",
    'total_groups': "• Totale Gruppi: {count}",
    'total_users': "• Totale Utenti: {count}",
    'total_admins': "• Totale Admin: {count}",
    'bot_version': "• Versione: 5.0",
}

# 17. Portuguese (Português) - Portugal
PT = {
    'name': 'Português',
    'country': '🇵🇹 Portugal',
    'flag': '🇵🇹',
    'welcome': "🌟 **Bem-vindo ao Mention Bot!** 🌟",
    'your_info': "**As suas informações:**",
    'user_id': "• O seu ID: `{user_id}`",
    'status': "• Estado: {status}",
    'admin_status': "👑 ADMIN",
    'user_status': "👤 UTILIZADOR",
    'owner': "• Dono do Bot: `{owner_id}`",
    'support_btn': "📞 Suporte",
    'add_btn': "➕ Adicionar ao Grupo",
    'settings_btn': "⚙️ Configurações",
    'language_btn': "🌐 Idioma",
    'commands_btn': "📋 Comandos",
    'close_btn': "❌ Fechar",
    'back_btn': "🔙 Voltar",
    'admin_only': "❌ Apenas admins podem usar este comando!",
    'group_only': "⚠️ Este comando só funciona em grupos!",
    'stopped': "⚠️ Menções paradas neste grupo. Use /resume para reiniciar.",
    'user_not_found': "❌ Utilizador não encontrado!",
    'promoted': "✅ **Admin Promovido!**",
    'demoted': "✅ **Admin Rebaixado!**",
    'already_admin': "⚠️ O utilizador já é admin!",
    'not_admin': "⚠️ O utilizador não é admin!",
    'broadcast_start': "📢 **Transmissão a começar...**",
    'broadcast_done': "✅ **Transmissão Concluída!**",
    'broadcast_usage': "⚠️ Uso: `/broadcast [mensagem]`",
    'stats_title': "📊 **Estatísticas do Bot**",
    'total_groups': "• Total de Grupos: {count}",
    'total_users': "• Total de Utilizadores: {count}",
    'total_admins': "• Total de Admins: {count}",
    'bot_version': "• Versão: 5.0",
}

# 18. Dutch (Nederlands) - Netherlands
NL = {
    'name': 'Nederlands',
    'country': '🇳🇱 Netherlands',
    'flag': '🇳🇱',
    'welcome': "🌟 **Welkom bij Mention Bot!** 🌟",
    'your_info': "**Uw informatie:**",
    'user_id': "• Uw ID: `{user_id}`",
    'status': "• Status: {status}",
    'admin_status': "👑 ADMIN",
    'user_status': "👤 GEBRUIKER",
    'owner': "• Bot-eigenaar: `{owner_id}`",
    'support_btn': "📞 Ondersteuning",
    'add_btn': "➕ Toevoegen aan Groep",
    'settings_btn': "⚙️ Instellingen",
    'language_btn': "🌐 Taal",
    'commands_btn': "📋 Commando's",
    'close_btn': "❌ Sluiten",
    'back_btn': "🔙 Terug",
    'admin_only': "❌ Alleen admins kunnen dit commando gebruiken!",
    'group_only': "⚠️ Dit commando werkt alleen in groepen!",
    'stopped': "⚠️ Mentions zijn gestopt in deze groep. Gebruik /resume om opnieuw te starten.",
    'user_not_found': "❌ Gebruiker niet gevonden!",
    'promoted': "✅ **Admin Gepromoveerd!**",
    'demoted': "✅ **Admin Gedegradeerd!**",
    'already_admin': "⚠️ Gebruiker is al admin!",
    'not_admin': "⚠️ Gebruiker is geen admin!",
    'broadcast_start': "📢 **Uitzending start...**",
    'broadcast_done': "✅ **Uitzending Voltooid!**",
    'broadcast_usage': "⚠️ Gebruik: `/broadcast [bericht]`",
    'stats_title': "📊 **Bot Statistieken**",
    'total_groups': "• Totaal Groepen: {count}",
    'total_users': "• Totaal Gebruikers: {count}",
    'total_admins': "• Totaal Admins: {count}",
    'bot_version': "• Versie: 5.0",
}

# 19. Polish (Polski) - Poland
PL = {
    'name': 'Polski',
    'country': '🇵🇱 Poland',
    'flag': '🇵🇱',
    'welcome': "🌟 **Witaj w Mention Bot!** 🌟",
    'your_info': "**Twoje informacje:**",
    'user_id': "• Twój ID: `{user_id}`",
    'status': "• Status: {status}",
    'admin_status': "👑 ADMIN",
    'user_status': "👤 UŻYTKOWNIK",
    'owner': "• Właściciel bota: `{owner_id}`",
    'support_btn': "📞 Wsparcie",
    'add_btn': "➕ Dodaj do Grupy",
    'settings_btn': "⚙️ Ustawienia",
    'language_btn': "🌐 Język",
    'commands_btn': "📋 Polecenia",
    'close_btn': "❌ Zamknij",
    'back_btn': "🔙 Wróć",
    'admin_only': "❌ Tylko admini mogą używać tego polecenia!",
    'group_only': "⚠️ To polecenie działa tylko w grupach!",
    'stopped': "⚠️ Wzmianki są zatrzymane w tej grupie. Użyj /resume aby wznowić.",
    'user_not_found': "❌ Nie znaleziono użytkownika!",
    'promoted': "✅ **Awans na Admina!**",
    'demoted': "✅ **Degradacja Admina!**",
    'already_admin': "⚠️ Użytkownik jest już adminem!",
    'not_admin': "⚠️ Użytkownik nie jest adminem!",
    'broadcast_start': "📢 **Rozpoczynanie transmisji...**",
    'broadcast_done': "✅ **Transmisja Zakończona!**",
    'broadcast_usage': "⚠️ Użycie: `/broadcast [wiadomość]`",
    'stats_title': "📊 **Statystyki Bota**",
    'total_groups': "• Łącznie Grup: {count}",
    'total_users': "• Łącznie Użytkowników: {count}",
    'total_admins': "• Łącznie Adminów: {count}",
    'bot_version': "• Wersja: 5.0",
}

# ==============================================
# SOUTH AMERICA
# ==============================================

# 20. Brazilian Portuguese (Português do Brasil) - Brazil
PT_BR = {
    'name': 'Português (Brasil)',
    'country': '🇧🇷 Brazil',
    'flag': '🇧🇷',
    'welcome': "🌟 **Bem-vindo ao Mention Bot!** 🌟",
    'your_info': "**Suas informações:**",
    'user_id': "• Seu ID: `{user_id}`",
    'status': "• Status: {status}",
    'admin_status': "👑 ADMIN",
    'user_status': "👤 USUÁRIO",
    'owner': "• Dono do Bot: `{owner_id}`",
    'support_btn': "📞 Suporte",
    'add_btn': "➕ Adicionar ao Grupo",
    'settings_btn': "⚙️ Configurações",
    'language_btn': "🌐 Idioma",
    'commands_btn': "📋 Comandos",
    'close_btn': "❌ Fechar",
    'back_btn': "🔙 Voltar",
    'admin_only': "❌ Apenas admins podem usar este comando!",
    'group_only': "⚠️ Este comando só funciona em grupos!",
    'stopped': "⚠️ Menções paradas neste grupo. Use /resume para reiniciar.",
    'user_not_found': "❌ Usuário não encontrado!",
    'promoted': "✅ **Admin Promovido!**",
    'demoted': "✅ **Admin Rebaixado!**",
    'already_admin': "⚠️ Usuário já é admin!",
    'not_admin': "⚠️ Usuário não é admin!",
    'broadcast_start': "📢 **Transmissão iniciando...**",
    'broadcast_done': "✅ **Transmissão Concluída!**",
    'broadcast_usage': "⚠️ Uso: `/broadcast [mensagem]`",
    'stats_title': "📊 **Estatísticas do Bot**",
    'total_groups': "• Total de Grupos: {count}",
    'total_users': "• Total de Usuários: {count}",
    'total_admins': "• Total de Admins: {count}",
    'bot_version': "• Versão: 5.0",
}

# 21. Argentine Spanish (Español Argentina) - Argentina
ES_AR = {
    'name': 'Español (Argentina)',
    'country': '🇦🇷 Argentina',
    'flag': '🇦🇷',
    'welcome': "🌟 **¡Bienvenido a Mention Bot!** 🌟",
    'your_info': "**Tu información:**",
    'user_id': "• Tu ID: `{user_id}`",
    'status': "• Estado: {status}",
    'admin_status': "👑 ADMIN",
    'user_status': "👤 USUARIO",
    'owner': "• Dueño del Bot: `{owner_id}`",
    'support_btn': "📞 Soporte",
    'add_btn': "➕ Añadir al Grupo",
    'settings_btn': "⚙️ Ajustes",
    'language_btn': "🌐 Idioma",
    'commands_btn': "📋 Comandos",
    'close_btn': "❌ Cerrar",
    'back_btn': "🔙 Volver",
    'admin_only': "❌ ¡Solo los admins pueden usar este comando!",
    'group_only': "⚠️ ¡Este comando solo funciona en grupos!",
    'stopped': "⚠️ Las menciones están detenidas en este grupo. Usa /resume para reiniciar.",
    'user_not_found': "❌ ¡Usuario no encontrado!",
    'promoted': "✅ **¡Admin Promovido!**",
    'demoted': "✅ **¡Admin Degradado!**",
    'already_admin': "⚠️ ¡El usuario ya es admin!",
    'not_admin': "⚠️ ¡El usuario no es admin!",
    'broadcast_start': "📢 **Transmisión comenzando...**",
    'broadcast_done': "✅ **¡Transmisión Completa!**",
    'broadcast_usage': "⚠️ Uso: `/broadcast [mensaje]`",
    'stats_title': "📊 **Estadísticas del Bot**",
    'total_groups': "• Total de Grupos: {count}",
    'total_users': "• Total de Usuarios: {count}",
    'total_admins': "• Total de Admins: {count}",
    'bot_version': "• Versión: 5.0",
}

# ==============================================
# AFRICA
# ==============================================

# 22. Nigerian English - Nigeria
EN_NG = {
    'name': 'Nigerian English',
    'country': '🇳🇬 Nigeria',
    'flag': '🇳🇬',
    'welcome': "🌟 **Welcome to Mention Bot!** 🌟",
    'your_info': "**Your Information:**",
    'user_id': "• Your ID: `{user_id}`",
    'status': "• Status: {status}",
    'admin_status': "👑 ADMIN",
    'user_status': "👤 USER",
    'owner': "• Bot Owner: `{owner_id}`",
    'support_btn': "📞 Support",
    'add_btn': "➕ Add to Group",
    'settings_btn': "⚙️ Settings",
    'language_btn': "🌐 Language",
    'commands_btn': "📋 Commands",
    'close_btn': "❌ Close",
    'back_btn': "🔙 Back",
    'admin_only': "❌ Only admins fit use this command!",
    'group_only': "⚠️ This command only works for groups!",
    'stopped': "⚠️ Mentions don stop for this group. Use /resume to start again.",
    'user_not_found': "❌ User no found!",
    'promoted': "✅ **Admin don get promotion!**",
    'demoted': "✅ **Admin don cast down!**",
    'already_admin': "⚠️ User don already be admin!",
    'not_admin': "⚠️ User no be admin!",
    'broadcast_start': "📢 **Broadcast dey start...**",
    'broadcast_done': "✅ **Broadcast don finish!**",
    'broadcast_usage': "⚠️ Use am well: `/broadcast [message]`",
    'stats_title': "📊 **Bot Statistics**",
    'total_groups': "• Total Groups: {count}",
    'total_users': "• Total Users: {count}",
    'total_admins': "• Total Admins: {count}",
    'bot_version': "• Version: 5.0",
}

# 23. South African English - South Africa
EN_ZA = {
    'name': 'South African English',
    'country': '🇿🇦 South Africa',
    'flag': '🇿🇦',
    'welcome': "🌟 **Welcome to Mention Bot!** 🌟",
    'your_info': "**Your Information:**",
    'user_id': "• Your ID: `{user_id}`",
    'status': "• Status: {status}",
    'admin_status': "👑 ADMIN",
    'user_status': "👤 USER",
    'owner': "• Bot Owner: `{owner_id}`",
    'support_btn': "📞 Support",
    'add_btn': "➕ Add to Group",
    'settings_btn': "⚙️ Settings",
    'language_btn': "🌐 Language",
    'commands_btn': "📋 Commands",
    'close_btn': "❌ Close",
    'back_btn': "🔙 Back",
    'admin_only': "❌ Only admins can use this command!",
    'group_only': "⚠️ This command only works in groups!",
    'stopped': "⚠️ Mentions are stopped in this group. Use /resume to start again.",
    'user_not_found': "❌ User not found!",
    'promoted': "✅ **Admin Promoted!**",
    'demoted': "✅ **Admin Demoted!**",
    'already_admin': "⚠️ User is already an admin!",
    'not_admin': "⚠️ User is not an admin!",
    'broadcast_start': "📢 **Broadcast starting...**",
    'broadcast_done': "✅ **Broadcast Complete!**",
    'broadcast_usage': "⚠️ Usage: `/broadcast [message]`",
    'stats_title': "📊 **Bot Statistics**",
    'total_groups': "• Total Groups: {count}",
    'total_users': "• Total Users: {count}",
    'total_admins': "• Total Admins: {count}",
    'bot_version': "• Version: 5.0",
}

# 24. Swahili (Kiswahili) - East Africa
SW = {
    'name': 'Kiswahili',
    'country': '🇹🇿 Tanzania / 🇰🇪 Kenya',
    'flag': '🇹🇿',
    'welcome': "🌟 **Karibu kwenye Mention Bot!** 🌟",
    'your_info': "**Taarifa zako:**",
    'user_id': "• ID yako: `{user_id}`",
    'status': "• Hali: {status}",
    'admin_status': "👑 ADMIN",
    'user_status': "👤 MTUMIAJI",
    'owner': "• Mmiliki wa Bot: `{owner_id}`",
    'support_btn': "📞 Msaada",
    'add_btn': "➕ Ongeza kwenye Kikundi",
    'settings_btn': "⚙️ Mipangilio",
    'language_btn': "🌐 Lugha",
    'commands_btn': "📋 Amri",
    'close_btn': "❌ Funga",
    'back_btn': "🔙 Rudi",
    'admin_only': "❌ Ni admin pekee wanaweza kutumia amri hii!",
    'group_only': "⚠️ Amri hii inafanya kazi kwenye vikundi tu!",
    'stopped': "⚠️ Mentions zimesimamishwa kwenye kikundi hiki. Tumia /resume kuanza tena.",
    'user_not_found': "❌ Mtumiaji hajakutikana!",
    'promoted': "✅ **Admin Imepandishwa!**",
    'demoted': "✅ **Admin Imeshushwa!**",
    'already_admin': "⚠️ Mtumiaji tayari ni admin!",
    'not_admin': "⚠️ Mtumiaji si admin!",
    'broadcast_start': "📢 **Matangazo yanaanza...**",
    'broadcast_done': "✅ **Matangazo yamekamilika!**",
    'broadcast_usage': "⚠️ Matumizi: `/broadcast [ujumbe]`",
    'stats_title': "📊 **Takwimu za Bot**",
    'total_groups': "• Jumla ya Vikundi: {count}",
    'total_users': "• Jumla ya Watumiaji: {count}",
    'total_admins': "• Jumla ya Admin: {count}",
    'bot_version': "• Toleo: 5.0",
}

# ==============================================
# LANGUAGE DICTIONARY - All 24 Languages
# ==============================================

LANGUAGES = {
    # India (3)
    'hi': HI,
    'en': EN,
    'sa': SA,
    
    # Asia (5)
    'id': ID,
    'ms': MS,
    'tl': TL,
    'th': TH,
    'vi': VI,
    
    # Middle East (3)
    'ar': AR,
    'tr': TR,
    'fa': FA,
    
    # Europe (7)
    'ru': RU,
    'de': DE,
    'fr': FR,
    'es': ES,
    'it': IT,
    'pt': PT,
    'nl': NL,
    'pl': PL,
    
    # South America (2)
    'pt_br': PT_BR,
    'es_ar': ES_AR,
    
    # Africa (3)
    'en_ng': EN_NG,
    'en_za': EN_ZA,
    'sw': SW,
}

# ==============================================
# LANGUAGE LIST FOR BUTTONS
# ==============================================

LANGUAGE_LIST = [
    # India (3)
    ('hi', '🇮🇳', 'हिंदी'),
    ('en', '🇬🇧', 'English'),
    ('sa', '🇮🇳', 'संस्कृतम्'),
    
    # Asia (5)
    ('id', '🇮🇩', 'Indonesia'),
    ('ms', '🇲🇾', 'Malaysia'),
    ('tl', '🇵🇭', 'Philippines'),
    ('th', '🇹🇭', 'ไทย'),
    ('vi', '🇻🇳', 'Tiếng Việt'),
    
    # Middle East (3)
    ('ar', '🇸🇦', 'العربية'),
    ('tr', '🇹🇷', 'Türkçe'),
    ('fa', '🇮🇷', 'فارسی'),
    
    # Europe (7)
    ('ru', '🇷🇺', 'Русский'),
    ('de', '🇩🇪', 'Deutsch'),
    ('fr', '🇫🇷', 'Français'),
    ('es', '🇪🇸', 'Español'),
    ('it', '🇮🇹', 'Italiano'),
    ('pt', '🇵🇹', 'Português'),
    ('nl', '🇳🇱', 'Nederlands'),
    ('pl', '🇵🇱', 'Polski'),
    
    # South America (2)
    ('pt_br', '🇧🇷', 'Português (Brasil)'),
    ('es_ar', '🇦🇷', 'Español (Argentina)'),
    
    # Africa (3)
    ('en_ng', '🇳🇬', 'Nigerian English'),
    ('en_za', '🇿🇦', 'South African English'),
    ('sw', '🇹🇿', 'Kiswahili'),
]

# ==============================================
# TOP LANGUAGES FOR QUICK ACCESS
# ==============================================

TOP_LANGUAGES = [
    ('hi', '🇮🇳', 'हिंदी'),
    ('en', '🇬🇧', 'English'),
    ('sa', '🇮🇳', 'संस्कृतम्'),
    ('id', '🇮🇩', 'Indonesia'),
    ('ms', '🇲🇾', 'Malaysia'),
    ('ar', '🇸🇦', 'العربية'),
    ('ru', '🇷🇺', 'Русский'),
    ('es', '🇪🇸', 'Español'),
    ('pt_br', '🇧🇷', 'Português'),
    ('fr', '🇫🇷', 'Français'),
]

# ==============================================
# FUNCTION TO GET LANGUAGE TEXT
# ==============================================

def get_text(lang_code, key, **kwargs):
    """Get text in specified language"""
    if lang_code not in LANGUAGES:
        lang_code = 'en'
    lang_dict = LANGUAGES[lang_code]
    text = lang_dict.get(key, LANGUAGES['en'].get(key, key))
    return text.format(**kwargs)
